id = "sql"
name = "SQL"
schema_version = 1
version = "1.1.6"
authors = ["nervenes", "notpeter", "phileix", "tammyxiong"]
description = "SQL language support."
repository = "https://github.com/zed-extensions/sql"

[grammars.sql]
repository = "https://github.com/DerekStride/tree-sitter-sql"
commit = "4a99c73f5384f2be10adc55208c84d95a7eb1137"
